package net.roburterra.guestbook.domain;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;

import java.util.Date;

@DynamoDBTable(tableName = "posts2")
public class GuestbookMessage {


    private String id;

    private String name,message,response,timestamp;

    public GuestbookMessage() {
    }

    @DynamoDBAttribute
    public String getTimestamp() {
        return timestamp;
    }

    public GuestbookMessage(String name, String message) {
        this.timestamp = new Date().toString();
        setName(name);
        setMessage(message);
    }

    public GuestbookMessage(String name, String message, String timestamp) {
        setTimestamp(timestamp);
        setName(name);
        setMessage(message);
    }

    @DynamoDBAttribute
    public String getName() {
        return name;
    }

    public void setName(String name) {
        if (name.length() > 25) //trim
            name = name.substring(0,24);

        this.name = name;
    }

    @DynamoDBAttribute
    public String getMessage() {
        return message;
    }

    public void setMessage(String message) {
        if (message.length()>300) //trim
            message = message.substring(0,499);
        this.message = message;
    }

    public String getResponse() {
        if (response == null) {
            return "";
        }
        return response;
    }

    @DynamoDBHashKey
    @DynamoDBAutoGeneratedKey
    public String getId() {
        return id;
    }

    public void setId(String id) {
        this.id = id;
    }

    public void setResponse(String response) {
        this.response = response;
    }

    public void setTimestamp(String timestamp) {
        this.timestamp = timestamp;
    }

    @Override
    public String toString() {
        return "GuestbookMessage{" +
                "name='" + name + '\'' +
                ", message='" + message + '\'' +
                ", response='" + response + '\'' +
                ", Timestamp='" + timestamp + '\'' +
                '}';
    }
}
